name: "ðŸ§ª Testing Issue"
description: Report issues with Vitest or Playwright tests
labels: ["Testing", "Needs Approval"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our test coverage! We use:
        - ðŸ§ª Vitest for unit/integration tests
        - ðŸŽ­ Playwright for E2E tests
        
        Please provide details about the testing issue or proposal.

  - type: dropdown
    id: test_type
    attributes:
      label: Test Type
      description: Which testing framework is involved?
      options:
        - "ðŸ§ª Vitest (Unit/Integration)"
        - "ðŸŽ­ Playwright (E2E)"
        - "ðŸ”§ Test Utils/Helpers"
        - "ðŸ“š Test Documentation"
    validations:
      required: true

  - type: dropdown
    id: issue_type
    attributes:
      label: Issue Type
      description: What type of testing issue is this?
      options:
        - "ðŸž Flaky Test"
        - "ðŸ” Missing Coverage"
        - "ðŸ”„ Test Improvement"
        - "âš¡ Test Performance"
        - "ðŸ—ï¸ Test Setup/Config"
    validations:
      required: true

  - type: input
    id: file
    attributes:
      label: Test File Location
      description: Which test file needs attention?
      placeholder: |
        e.g., src/__tests__/component.test.ts
        or e2e/flows/auth.spec.ts
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: |
        Please describe the testing issue:
        - For flaky tests: Include failure rate and conditions
        - For missing coverage: What scenarios need testing?
        - For improvements: What could be better?
      placeholder: |
        The Playwright test fails intermittently when...
        or
        We're missing Vitest coverage for...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: |
        How can we reproduce the issue?
        Include specific test commands and environment details.
      placeholder: |
        1. Run `pnpm test:e2e path/to/test` or `pnpm test:unit path/to/test`
        2. Observe behavior
        3. Error message:
        ```
        Error details here
        ```
    validations:
      required: false

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: |
        How do you suggest we fix this?
        - For Vitest: Unit test improvements?
        - For Playwright: E2E scenario changes?
        - For setup: Configuration updates?
      placeholder: |
        We could:
        1. Add test for edge case X
        2. Update Playwright config for Y
        3. Improve Vitest setup for Z
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Example Code
      description: |
        Include relevant test code or proposed test cases.
        Use code blocks for formatting.
      placeholder: |
        ```typescript
        // For Vitest
        describe('Component', () => {
          it('should handle case', () => {
            // Test code
          })
        })

        // For Playwright
        test('flow', async ({ page }) => {
          // Test steps
        })
        ```
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: |
        Please provide:
        - Node.js version
        - Playwright version
        - Vitest version
        - OS/Browser details
        - CI/Local execution
      placeholder: |
        Node.js: 18.x
        Playwright: 1.x
        Vitest: 1.x
        OS: Ubuntu 22.04
        Browser: Chromium
        Environment: CI
    validations:
      required: false 