-- Migration generated by C15T (2023-01-01T00:00:00.000Z)
-- Database type: postgresql
-- Description: Automatically generated schema migration
-- 
-- Wrapped in a transaction for atomicity
-- To roll back this migration, use the ROLLBACK section below

BEGIN;
-- MIGRATION
CREATE TABLE IF NOT EXISTS "subject" (
  "id" varchar(255) NOT NULL PRIMARY KEY,
  "isIdentified" boolean NOT NULL,
  "externalId" text,
  "identityProvider" text,
  "lastIpAddress" text,
  "createdAt" timestamp with time zone NOT NULL,
  "updatedAt" timestamp with time zone NOT NULL,
  "subjectTimezone" text
);

CREATE TABLE IF NOT EXISTS "consentPurpose" (
  "id" varchar(255) NOT NULL PRIMARY KEY,
  "code" varchar(255) NOT NULL,
  "name" varchar(255) NOT NULL,
  "description" varchar(255) NOT NULL,
  "isEssential" boolean NOT NULL,
  "dataCategory" text,
  "legalBasis" text,
  "isActive" boolean NOT NULL,
  "createdAt" timestamp with time zone NOT NULL,
  "updatedAt" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "domain" (
  "id" varchar(255) NOT NULL PRIMARY KEY,
  "name" varchar(255) NOT NULL UNIQUE,
  "description" varchar(255),
  "allowedOrigins" text,
  "isVerified" boolean NOT NULL,
  "isActive" boolean NOT NULL,
  "createdAt" timestamp with time zone NOT NULL,
  "updatedAt" timestamp with time zone
);

CREATE TABLE IF NOT EXISTS "geoLocation" (
  "id" varchar(255) NOT NULL PRIMARY KEY,
  "countryCode" text NOT NULL,
  "countryName" text NOT NULL,
  "regionCode" text,
  "regionName" text,
  "regulatoryZones" text,
  "createdAt" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "consentPolicy" (
  "id" varchar(255) NOT NULL PRIMARY KEY,
  "version" text NOT NULL,
  "name" varchar(255) NOT NULL,
  "effectiveDate" date NOT NULL,
  "expirationDate" date,
  "content" text NOT NULL,
  "contentHash" text NOT NULL,
  "isActive" boolean NOT NULL,
  "createdAt" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "consent" (
  "id" varchar(255) NOT NULL PRIMARY KEY,
  "subjectId" text NOT NULL REFERENCES "subject" ("id"),
  "domainId" text NOT NULL REFERENCES "domain" ("id"),
  "purposeIds" text,
  "metadata" jsonb,
  "policyId" text REFERENCES "consentPolicy" ("id"),
  "ipAddress" text,
  "userAgent" text,
  "status" text NOT NULL,
  "withdrawalReason" text,
  "givenAt" date NOT NULL,
  "validUntil" date,
  "isActive" boolean NOT NULL
);

CREATE TABLE IF NOT EXISTS "consentPurposeJunction" (
  "id" varchar(255) NOT NULL PRIMARY KEY,
  "consentId" text NOT NULL REFERENCES "consent" ("id"),
  "purposeId" text NOT NULL REFERENCES "consentPurpose" ("id"),
  "status" text NOT NULL,
  "metadata" jsonb,
  "createdAt" timestamp with time zone NOT NULL,
  "updatedAt" timestamp with time zone
);

CREATE TABLE IF NOT EXISTS "consentRecord" (
  "id" varchar(255) NOT NULL PRIMARY KEY,
  "subjectId" text NOT NULL REFERENCES "subject" ("id"),
  "consentId" text REFERENCES "consent" ("id"),
  "actionType" text NOT NULL,
  "details" text,
  "createdAt" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "consentGeoLocation" (
  "id" varchar(255) NOT NULL PRIMARY KEY,
  "consentId" text NOT NULL REFERENCES "consent" ("id"),
  "ip" text NOT NULL,
  "country" text,
  "region" text,
  "city" text,
  "latitude" integer,
  "longitude" integer,
  "timezone" text,
  "createdAt" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "consentWithdrawal" (
  "id" varchar(255) NOT NULL PRIMARY KEY,
  "consentId" text NOT NULL REFERENCES "consent" ("id"),
  "subjectId" text NOT NULL REFERENCES "subject" ("id"),
  "withdrawalReason" text,
  "withdrawalMethod" text NOT NULL,
  "ipAddress" text,
  "userAgent" text,
  "metadata" jsonb,
  "createdAt" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "auditLog" (
  "id" varchar(255) NOT NULL PRIMARY KEY,
  "entityType" text NOT NULL,
  "entityId" text NOT NULL,
  "actionType" text NOT NULL,
  "subjectId" text REFERENCES "subject" ("id"),
  "ipAddress" text,
  "userAgent" text,
  "changes" text,
  "metadata" jsonb,
  "createdAt" timestamp with time zone NOT NULL,
  "eventTimezone" text NOT NULL
);
COMMIT;

-- ROLLBACK
-- Uncomment the section below to roll back this migration
/*
BEGIN;

DROP TABLE IF EXISTS "auditLog";

DROP TABLE IF EXISTS "consentWithdrawal";

DROP TABLE IF EXISTS "consentGeoLocation";

DROP TABLE IF EXISTS "consentRecord";

DROP TABLE IF EXISTS "consentPurposeJunction";

DROP TABLE IF EXISTS "consent";

DROP TABLE IF EXISTS "consentPolicy";

DROP TABLE IF EXISTS "geoLocation";

DROP TABLE IF EXISTS "domain";

DROP TABLE IF EXISTS "consentPurpose";

DROP TABLE IF EXISTS "subject";

COMMIT;
*/