import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import {
	ConsentManagerDialog,
	ConsentManagerProvider,
	CookieBanner,
} from '@c15t/nextjs';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ConsentManagerProvider
					options={{
						mode: 'c15t',
						backendURL: '/api/c15t',
						consentCategories: ['necessary', 'marketing'], // Optional: Specify which consent categories to show in the banner.
						ignoreGeoLocation: true, // Useful for development to always view the banner.
					}}
				>
					<CookieBanner />
					<ConsentManagerDialog />

					{children}
				</ConsentManagerProvider>
			</body>
		</html>
	);
}
