// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index = {
	default: {
		"consent-solution": {
			name: "consent-solution",
			description: "",
			type: "registry:ui",
			registryDependencies: [],
			files: [
				{
					path: "registry/default/components/consent/cookie-banner.tsx",
					type: "registry:ui",
					target: "components/consent/cookie-banner.tsx",
				},
				{
					path: "registry/default/components/consent/overlay.tsx",
					type: "registry:ui",
					target: "components/consent/overlay.tsx",
				},
				{
					path: "registry/default/components/consent/consent-customization-dialog.tsx",
					type: "registry:ui",
					target: "components/consent/consent-customization-dialog.tsx",
				},
				{
					path: "registry/default/components/consent/consent-customization-widget.tsx",
					type: "registry:ui",
					target: "components/consent/consent-customization-widget.tsx",
				},
			],
			categories: undefined,
			component: React.lazy(
				() => import("@/registry/default/components/consent/cookie-banner.tsx"),
			),
			source: "",
			meta: undefined,
		},
		utils: {
			name: "utils",
			description: "",
			type: "registry:lib",
			registryDependencies: undefined,
			files: [
				{
					path: "registry/default/lib/utils.ts",
					type: "registry:lib",
					target: "",
				},
			],
			categories: undefined,
			component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
			source: "",
			meta: undefined,
		},
		"consent-solution-demo": {
			name: "consent-solution-demo",
			description: "",
			type: "registry:example",
			registryDependencies: ["consent-solution"],
			files: [
				{
					path: "registry/default/examples/consent-solution-demo.tsx",
					type: "registry:example",
					target: "",
				},
			],
			categories: undefined,
			component: React.lazy(() => import("@/registry/default/examples/consent-solution-demo.tsx")),
			source: "",
			meta: undefined,
		},
		"consent-solution-minimal-demo": {
			name: "consent-solution-minimal-demo",
			description: "",
			type: "registry:example",
			registryDependencies: ["consent-solution"],
			files: [
				{
					path: "registry/default/examples/consent-solution-minimal-demo.tsx",
					type: "registry:example",
					target: "",
				},
			],
			categories: undefined,
			component: React.lazy(
				() => import("@/registry/default/examples/consent-solution-minimal-demo.tsx"),
			),
			source: "",
			meta: undefined,
		},
		"consent-solution-callback-demo": {
			name: "consent-solution-callback-demo",
			description: "",
			type: "registry:example",
			registryDependencies: ["consent-solution"],
			files: [
				{
					path: "registry/default/examples/consent-solution-callback-demo.tsx",
					type: "registry:example",
					target: "",
				},
			],
			categories: undefined,
			component: React.lazy(
				() => import("@/registry/default/examples/consent-solution-callback-demo.tsx"),
			),
			source: "",
			meta: undefined,
		},
		"dev-tool-example": {
			name: "dev-tool-example",
			description: "",
			type: "registry:example",
			registryDependencies: ["consent-solution"],
			files: [
				{
					path: "registry/default/examples/dev-tool-example.tsx",
					type: "registry:example",
					target: "",
				},
			],
			categories: undefined,
			component: React.lazy(() => import("@/registry/default/examples/dev-tool-example.tsx")),
			source: "",
			meta: undefined,
		},
	},
};
